name: 'Pipeline Silver - br_ibge_municipio'

on:
  # schedule:
  #   - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  br_ibge_municipio:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      DBT_PROFILES_DIR: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Install dependencies
        working-directory: pipelines/silver/br_ibge_municipio
        run: |
          pip install -r requirements.txt

      - name: Run pipeline silver.br_ibge_municipio
        working-directory: pipelines/silver/br_ibge_municipio
        run: |
          python pipeline.py